### ISSUE TITLE
Problem Statement Review

### ISSUE THREAD

**Issue by GenevaS** [GenevaS/CAS741#1]
Hi Professor.

I've finished the initial draft of the problem statement, which hopefully answers most of the questions that were brought up earlier today. Please let me know if anything is still unclear, or if the project idea needs to be revised.

Thanks!

**Comment by smiths** [comment]
Hello Geneva.  Your project sounds good.  I did commit a new version with a very minor spelling correction.  (You can see it using diff.)  

Can you please clarify how CCC is related to AI.  The description should be abstract, but what you have written doesn't really give me a clue of why this tool will be useful for games.

**Comment by GenevaS** [comment]
Hi Professor.

I have clarified that this is to help with the development of GLaDOS and added an additional environment constraint should a GUI interface be desired. Please let me know if there are additional points to clarify.

These changes were made in 3ea618971fde4348b7973a8c1709eb204dc0a8ce

The files can be found at:
https://github.com/GenevaS/CAS741/blob/master/Documentation/ProblemStatement/ProblemStatement.pdf
https://github.com/GenevaS/CAS741/blob/master/Documentation/ProblemStatement/ProblemStatement.tex

**Comment by smiths** [comment]
Looks great!  Problem statement approved!
