### ISSUE TITLE
SRS Comments: Implication of Behaviour on Unsupported Interval

### ISSUE THREAD

**Issue by GenevaS** [GenevaS/CAS741#12]
\subsection{Scope of Requirements} 
The \prognameAbbrv{} calculates $R(f(X))$ of a user-defined $f(X)$ and $D(x), x 
\in X$. Each $D(x)$ must be specified by the user in the initial version of 
this tool, otherwise the unsupported interval $(-\infty, \infty)$ will be 
assumed (\aref{A_domain}).  

**\wss{This is confusing.  I would guess if the
  assumption were violated that the program would not calculate a result, but
  you seem to be suggesting otherwise.}**

**Comment by smiths** [comment]
It seems like I'm being asked a question, given the label, but I do not know what the question is.  😄   The word "unsupported" is the main thing that confuses me.  If it isn't supported, how can it be used?

**Comment by GenevaS** [comment]
I guess the question here would be should I remove this? I realize that in my test plan I am writing test cases to report to the user when a domain interval is missing or incomplete. This would leave:

"The C^3 calculates ``R(f(X))`` of a user-defined ``f(X)`` and ``D(x), x \in X``. Each ``D(x)`` must be specified by the user in the initial version of this tool, otherwise the tool will assume that the user input set is incomplete and treat it as an error."

**Comment by smiths** [comment]
I think your requirements should reflect what you are saying in your test cases.  (This is why we are faking a rational design process.)  😄   You can say in your requirements that if D(x) is not specified this will be reported to the user, or whatever you require.

**Comment by GenevaS** [comment]
Alright, I have made the change. If you are satisfied that this clears the misunderstanding I will close the issue.

**Comment by smiths** [comment]
Looks good.  I'll close the issue for you.  😄
