### ISSUE TITLE
SRS Comments: Reducing Mathematical Notation in Goal Statements

### ISSUE THREAD

**Issue by GenevaS** [GenevaS/CAS741#13]
\item[GS\refstepcounter{goalnum}\thegoalnum \label{G_range}:] 
Calculate $R(f(X))$.

%\item[GS\refstepcounter{goalnum}\thegoalnum \label{G_unknownDomain}:] 
%Determine $D(x)$ for any $x \in X$ if it is not part of the input set.

**\wss{Your goal statement is more mathematical than usual.  It is nice if the
  goal statement can be written with a minimal amount of mathematical notation,
  so that as large an audience as possible can understand it.}**

**Comment by smiths** [comment]
@GenevaS, I like your approach of creating issues for each of my comments.  However, please only add me as an assignee if I am actually assigned to do something.  If you are assigning me to do something, you'll need to be more clear on what I'm expected to do.

Even if I'm not assigned, I'll see all of the issues that you create, because I am "watching" your repo.

**Comment by GenevaS** [comment]
Sorry about that...I will immediately follow up with the two issues I assigned to you.

Could this issue be addressed with this expanded description?

"Given a user-defined function (``f(X)``) with any number of variables (``x_0, ..., x_n``) and the domains of those variables (``D(x_0), ..., D(x_n)``), the goal of the C^3 tool is:

GS1: Calculate the range of ``f(X)`` (``R(f(X))``)."

**Comment by smiths** [comment]
Can you try a version that is mostly in words?  That is, what will it sound like if you expand the words domain and range into words?  If possible, I'd like the goal to be something that doesn't require any mathematical sophistication to read.

**Comment by GenevaS** [comment]
Sure, but shouldn't this be alright because my intended reader should understand what domain and range are?

"Given a user-defined function (``f(X)``) with any number of variables (``x_0, ..., x_n``) and the minimum and maximum values that those variables can take (``D(x_0), ..., D(x_n)``), the goal of the C^3 tool is:

GS1: Calculate the minimum and maximum values (``R(f(X))``) for ``f(X)``."

**Comment by smiths** [comment]
I prefer the goal to be as simple to read as possible by as wide an audience as possible, but you can leave it as it is, if that is your preference.

**Comment by GenevaS** [comment]
Is the last revision I sent still to math-heavy? Or is there too much notation (even if it is just for referencing other document elements)?

**Comment by smiths** [comment]
Hello Geneva.  My intuition is that you could write your goal statement with no (or almost no) math.  I have a feeling that this might lead to a better goal statement, but until I see it written out, it is only intuition.  Once I saw it, I might change my mind.  😄  If your intuition doesn't agree, then you can leave it as it is.  The decision is yours.

**Comment by GenevaS** [comment]
Ok then, if I remove all of the notation I am left with:

"Given a user-defined function, which can contain any number of variables, and the minimum and maximum values for each variable in the user-defined function, the goal of the C^3 tool is:

GS1: Determine the minimum and maximum values that the user-defined function can achieve."

**Comment by smiths** [comment]
That sounds great to me!  My mother could understand that goal.  😄 (That is one of my tests for whether a goal is understandable to a wide audience.)  

In my opinion, the mathematical way of saying the above is one of your instance models.

I prefer your new goal to the original, but the decision is yours.

**Comment by GenevaS** [comment]
You have been doing this longer than I have, so I will defer to your judgement for now :)

I have replaced the original goal with the new one, so I think this issue can be closed.
