### ISSUE TITLE
SRS Comments: Combining Theoretical Models

### ISSUE THREAD

**Issue by GenevaS** [GenevaS/CAS741#14]
\wss{T1 to T4 are very similar.  You could consider combining them and
  abstracting out the binary operator.  You could add a constraint for the case
  where the binary operator is division.}

**Comment by GenevaS** [comment]
I would be happy to combine the models for addition, subtraction, and multiplication, but I think I would like to keep division separate. I believe that it is "different enough" from a mathematical definition. What do you think?

**Comment by smiths** [comment]
Your plan sounds good to me.

**Comment by GenevaS** [comment]
Alright, the changes have been implemented in 5423998c902136e0689881b4ebc57ac1c15ad81a. The traceability table and chart for models and data definitions were also affected.

Does the presentation of the new model make sense with the temporary ``<op>`` variable? Should this also be added to the notations reference table (I think your answer will be yes to this one, but I want to be sure)?

**Comment by smiths** [comment]
Hello Geneva.  You'll want to move op outside of your set building notation.  You are writing a template for these sets, not one set that includes all of them.  Yes, I would add this to your notations reference table.  😄

**Comment by GenevaS** [comment]
Ok, I lift the ``op`` variable out so that the equation now reads (the description is unchanged, just added for reference here):

**Equation**:  ``X <op> Y = {x <op> y | x \in X \wedge y \in Y\}, where op \in {+, -, x}``
**Description**: The summation, subtraction, and multiplication interval of two   real intervals ``X`` and ``Y`` is equal to the set of sums, differences, and products for each pairwise element ``x`` and ``y``.

And added the notation:

``op`` (No type) A temporary set of mathematical operators used to define equation templates

If this is satisfactory, we can close this issue :)

**Comment by smiths** [comment]
This is mostly better, but op has type.  You can see this in ghci by typing the following at the prompt:

:type (+)

**Comment by GenevaS** [comment]
I don't have ghci handy, but I am guessing that the type is ``Real -> Real -> Real``?

**Comment by smiths** [comment]
Yes, you have the right idea.  So, op has a type.

(Technically, ghci returns:
(+) :: Num a => a -> a -> a)

😄

**Comment by GenevaS** [comment]
Ok, got it. I now have the notation reference:

``op`` (Type -> Type -> Type)  A temporary set of mathematical operators used to define equation templates; the type of the equation is determined by the type of the input values

**Comment by GenevaS** [comment]
Was the type of ``op`` the last fix related to this issue?

**Comment by smiths** [comment]
No other thoughts occur to me at this time.  I'll close this issue.
