### ISSUE TITLE
SRS Comments: Theoretical Model for Constant Exponents on a Real Interval Base

### ISSUE THREAD

**Issue by GenevaS** [GenevaS/CAS741#15]
\wss{This does not make sense to me.  It does not match what I see at the
  wikipedia page.  Is $X$ an interval, or is $X$ a set of intervals, or is $X$ a
  set of variables?  What is the subscript $z$?}

**Comment by GenevaS** [comment]
This might be a case of notation again. I would have liked a better source for this, but I could not find any in my brief search.

Wikipedia's model seemed more like an "instance" model to me, so I expanded it into what I expect the original theoretical model was. What I ended up with was an interval ``X`` raised to the power of ``n``. Since I had already used ``n`` to represent exponents, I had to use another variable (in this case, ``z``) to denote variable numbering subscripts (Wikipedia got around this by simply naming the interval bounds and calling them ``x_1`` and ``x_2``). 

Please tell me if this explanation makes sense.

**Comment by smiths** [comment]
I think you need to provide the type information here.   Your explanation above explains the z, but the notation overall is still confusing.  To start with, you seem to be over using the symbol X.  Outside of T6, X is a set of variables.  Inside T6, X seems to be an interval.  However, the intervals have ... in the middle: [x_1^N, ..., x_z^N].  Do you want this "..."?  What does it mean?

**Comment by GenevaS** [comment]
Maybe the new notations from d216c7d273c9fd989238b07ea4768eed199949b1 addresses this confusion?

**Comment by smiths** [comment]
What is the type of X here?

**Comment by GenevaS** [comment]
It is the same (or should be the same) as the other instances of ``X`` in the theoretical models:

"``X`` (``{R, ..., R}``) A closed, connected set of real values"

**Comment by smiths** [comment]
In your middle two cases you (N is even), you have square brackets.  I don't know what those mean in this context?  Is this a tuple?  If it is, then it doesn't match the set that you propose.   Is it an interval?  No, because it has more than two entries.  You also mix sequence and set, since you have subscripts.

**Comment by GenevaS** [comment]
Ok, I see now. Updating the equation in the ELSE clause is easy enough:

``{x^N | 0 <= x^N <= max(x_1^N,x_n^N) ^ x \in X ^ N \in NaturalNumbers}``

I don't know about converting the ``N is even`` cases because of the ordering of the elements. I tried using partially ordered set notation. Does this make any sense?

``{x^N | x \in X ^ N \in NaturalNumbers}, (X^N, <) when N is even ^  x_{n} >= x_{n+1} ^ x_{1} > 0``
``{x^N | x \in X ^ N \in NaturalNumbers}, (X^N, >) when N is even ^ x_{n+1} < x_{n+2} ^ x_{n} < 0``

**Comment by smiths** [comment]
Hello Geneva.  I feel bad saying this, but I don't have time at the moment to go through the details.  It doesn't take much time for me to say when something looks wrong, but it does take time to specifically say how to get it right.  😄 My advice to you is to either get a colleague to help, or to relax your goal of abstraction and just say it the same way that your original Wikipedia source said it.  I agree with your goal of being abstract, but if it is too difficult to say correctly, using the simpler model where you represent the interval with bounds is fine.

**Comment by GenevaS** [comment]
Not your fault - I know that you have a lot of work to do :) I will ask Dr. Carette about this when I see him for our meeting on Tuesday.

**Comment by smiths** [comment]
Thank you Geneva.  It is also an issue of fairness.  I do not want to spend dramatically more time on one students assignment over that of the others.

**Comment by GenevaS** [comment]
Alright, I think Dr. Carette and I figured out what was wrong with this definition. I have made the changes if you would verify that it now makes sense.

This also brings up a secondary question - neither of the exponent theoretical models are explicitly defined at the source I gave. They are only implied. Should I remove the source and leave it empty or leave it as is?

**Comment by smiths** [comment]
This is definitely better, but I don't understand the case for N is even and 0 >= a and a > b.  For your intervals I believe you are assuming that a <= b.  At least based on your terminology definitions on page 4, and the usual usage of this notation.  That means that this case will never occur.  I think you might want to have another look at the wikipedia page that you cited.  😄 

In answer to your other question - yes,  you should keep the reference to the source material.  It gives the interested reader something to follow up with.  If you think the connection between the source and the current material ever needs to be explained, you could add some text to make the connection for the reader.

**Comment by GenevaS** [comment]
This is in the instance model, not the theoretical model?

**Comment by GenevaS** [comment]
Found the error, thanks!
