### ISSUE TITLE
SRS Comments: Instance Model for Calculating f(X)

### ISSUE THREAD

**Issue by GenevaS** [GenevaS/CAS741#16]
\wss{You don't actually have an instance model to calculate the range of $f$.
  Something like slide 13 of the previously mentioned slides might be appropriate?}

**Comment by GenevaS** [comment]
I do talk about this though:

"The goal \gsref{G_range} is solved by recursively solving instance models 
\iref{I_addition}, \iref{I_subtraction}, \iref{I_multiplication}, 
\iref{I_positivedivision}, \iref{I_negativedivision}, \iref{I_exponents}, and 
\iref{I_expbase} and combining the results. For example, if the user provided 
an equation of the form ``a + b * c``, it is decomposed into ``a + B`` where 
``B = b * c``. This approach is identical to a hand-written evaluation where 
the intermediary decomposition stages are commonly omitted by humans."

I don't know how you would make this into its own separate model because I am just passing the output from one model as input to another.

**Comment by smiths** [comment]
I think what you have written would work fine as an instance model.  It gets lost if the information is just in a paragraph introducing the other instance models.  Also, having an instance model for this will allow you to have explicit traceability to your goal.

**Comment by GenevaS** [comment]
I have added an instance model for composing operators. Would you have a quick look to see if it makes sense please?

**Comment by smiths** [comment]
I would have thought IM8 would be a recursive definition.  I didn't think of this earlier, but you don't have any unary operators?

**Comment by GenevaS** [comment]
The only unary operator I support is (-) so that negative numbers can be represented, although this is only implicitly stated. I don't think there would be any associated models, so this might be something to add to the requirement scope section.

For the recursive definition, maybe something like:

```
Input: f(V), [a_1, b_1], ..., [a_n, b_n] from DD1 for each v \in V
Output: R(f(V)) = [a_R, b_R] such that

R(f(V)) = [a_i, b_i], V = {v_i}
R(f(V_1), f(V_2)) = R(f(V_1)) <op> R(f(V_2)) , f(V_1) = f(V - V_2) AND f(V_2) = f(V - V_1) 

<op> can be any supported binary operator (A3)
R(f(V)) = [a_R, b_R] is a closed, real interval (A2)
```

**Comment by smiths** [comment]
Hi Geneva.  Your new definition doesn't really lead to the base case.  I think you have the right idea, but the notation still seems odd.  You don't have to invent anything here.  If you google terms like:

compiler example calculator
bnf arithmetic expression

You will get many hits and examples.  These examples might also explicitly show the unary operator for minus.  😄 I sat in on one of Jacques programming language classes and his lecture covered much of this material.  I don't know if you took the programming language course, but if you did, then I think it would be helpful here.

**Comment by GenevaS** [comment]
The problem with the way that it is presented for programming is that it is treated as a language grammar, not strictly as a recursive definition as it would appear in mathematics. 

I will look into that further, but I think the base case should be:

``R(f(V_1), f(V_2)) = [a_1, b_1] <op> [a_2, b_2], V_1 = {v_i} AND V_2 = {v_j} AND i,j <= n AND  i != j``

As for negation, I think I would have to add a new set of models (theoretical and instance) as well as changing the operator assumption to include it. I only thought about it in terms of constant numbers (e.g. -2, not -x), but it would be a useful addition. Thoughts?

**Comment by GenevaS** [comment]
I have rewritten the equation as a BNF, but I am not sure if this would be considered inconsistent with the rest of the document or not. What do you think?

**Comment by smiths** [comment]
I wouldn't worry about BNF being inconsistent with the rest of the document.

**Comment by GenevaS** [comment]
Alright. This addition also prompted me to add some new requirements for it, but Iwonder if at least one of them is redundant?

**Comment by GenevaS** [comment]
I think this issue can be closed if you think the instance model for this makes sense. I will take care of any ambient issues that came up because of this change :)
