### ISSUE TITLE
SRS Comments: Directed Rounding

### ISSUE THREAD

**Issue by GenevaS** [GenevaS/CAS741#17]
\wss{You haven't mentioned directed rounding.  Is that relevant for your
  problem.  Of course it isn't a concern for real numbers and exact arithmetic,
  but mentioning the assumed differences from floating point arithmetic makes
  sense to me.}

**Comment by GenevaS** [comment]
I don't know how directed rounding comes into this when I am assuming either real numbers (which can have fractions so I am not concerned with rounding off their values) or natural numbers (which cannot have fractions or else it is an error). Do you mean with respect to the output? If that is the case, I have specified a reliability non-functional requirement that covers floating point error rates.

**Comment by smiths** [comment]
When you mention fractions, do you mean that you are using rational numbers?  This isn't the same as real numbers.  Are you tracking the numerator and the denominator?  If not, you are introducing an error in some cases, since not every fraction (rational number) can be represented exactly be a floating point number.  For instance, 1/10 cannot be stored exactly as a floating point number.

I'm not talking about floating point error, I'm talking about the related concept of containment.  The big thing with interval arithmetic is that the answer is guaranteed to lie between the bounds.  It isn't close to the bounds, it is between (or on) the bounds.  This is why directed rounding is used, so that containment is always conservative.

Adding a nonfunctional requirement on containment would help.

**Comment by GenevaS** [comment]
Yes, I do mean real (i.e. floating point) numbers because that is the domain the equations will ultimately be used in (game engine). This would imply (at least to me) that rounding error from floating point calculations will have little to no affect on the results.

I still don't understand how containment is related to my application specifically. The bounds that I am calculating are not error bounds - I am calculating the minimum and maximum values that an equation can take. I just happened to choose interval arithmetic as the means to get those values. I don't think that rounding wouldn't be useful in this sense, especially since I am explicitly using closed intervals.

**Comment by smiths** [comment]
I'm confused by your last post.  When you say real, do you mean floating point?  Floating point and real are not the same thing.  If you want an approximate range for your function, then you don't have to worry about floating point numbers.  You will probably get the right result most of the time.  Given your use of intervals, I had assumed that you wanted the exact range.  Either way, your requirements should make your choice clear.

As an example, if exact (mathematical) domain is [0, 1], would you be fine with the result [0, 1.00001]?  If that is fine, you can state your requirements to clarify that your goal is not containment of the correct bounds, only to achieve approximate bounds.

**Comment by GenevaS** [comment]
Maybe it would help (me as well) if I explained what the range will be used for? In the context of equations for other applications, I had intended the range to be used to normalize a calculation. For example, if the range is calculated to be [0,34], in practice I would use it to normalize the results to [0,1]. 

So now I am unsure if I would need directed rounding or not. On one hand, I want the range to be as precise as possible. However, if I am only using it to normalize results, how would the rounding help? Wouldn't rounding actually cause errors in the normalization process that follows?

**Comment by smiths** [comment]
My guess is that the answers without directed rounding will be fine for your purpose.  I think you should just say this in your SRS.  If it turns out to not be adequate, you can revise your SRS and "fake it" like you always knew it would be an issue.  😄

**Comment by GenevaS** [comment]
That would be my suspicion as well, which is probably why I didn't think of it until now.

The comment that mentions this is at the bottom of the Instance Models section, but would I be correct in assuming that this is a "Scope of Requirements" or a "Data Constraints" section piece?

**Comment by smiths** [comment]
The Scope section sounds like a good place.

**Comment by GenevaS** [comment]
Alright, I made the addition. Please let me know if further adjustments are needed regarding directed rounding for this specification.

**Comment by GenevaS** [comment]
Do you think that this question has been addressed adequately? I so, please close this issue. If not, what else do you feel is missing?
