### ISSUE TITLE
Section 1: Introduction

### ISSUE THREAD

**Issue by GenevaS** [GenevaS/CAS741#2]
Hi Professor. I have a number of clarification questions for the first section of the SRS that should (hopefully) be easy to answer:

1. The Introduction preamble should only state what product the SRS is for, a (very) short explanation of what that is and a (very) short explanation of why, correct? Otherwise there would be a lot of repetition in the subsections I think.
2. Does the "Purpose" section contain the same information as the "Purpose" section in the IEEE template (i.e. why the SRS is being written and for whom)?
3. Same question for the "Scope of Requirements" section (with the exception of product goals, which have their own section later) -> does it contain the same information as the IEEE SRS (identify product by name, identify what it will/will not do, describe intended benefits and objectives)?
4. I believe that the "intended readers" and "intended users" are the same for my project. Should I duplicate the information (one for each section), or write one and refer to it from the other section?

The paper "A New Requirements Template for Scientific Computing" does not seem to specify this information, which is why I am defaulting to the IEEE template outline for now. 

Here is the reference I am using when talking about the IEEE template: http://www.cse.msu.edu/~cse870/IEEEXplore-SRS-template.pdf

**Comment by smiths** [comment]
Hello Geneva.  Great questions!  Thank you.

Yes, the introduction should be at a high level.  The document is intended to proceed from abstract to concrete, or general to specific.  The introduction should be short.  There is some repetition in the document, the human reader usually appreciates this.

Yes, the purpose section should follow the IEEE template and the same for the scope.

If intended readers and intended users are the same, then you should not repeat the information.  You should include it once, and then reference the other location.

I'll add the IEEE template to our cas741 repo.  (I actually thought it was already in there.)  😄

**Comment by GenevaS** [comment]
Ok, thank you!
