### ISSUE TITLE
SRS: Changing the Reliability Non-Functional Requirement

### ISSUE THREAD

**Issue by GenevaS** [GenevaS/CAS741#20]
I was thinking about the reliability non-functional requirement (which talks about being correct within the floating point error of the machine), and I believe this should be about rounding to significant digits instead. Since I don't especially care about floating point error (hence the directed rounding questions), I think what I am really interested in is the rounding for significant digits (e.g. if the precision of one value is two decimal places, all values should be rounded to two decimal places). 

What do you think?

**Comment by smiths** [comment]
If you are just talking about how many digits of precision, this is a straightforward requirement.  You would just be talking about how many digits to display.  However, if you want the digits to be accurate, then you are back to worrying about floating point error.  Significant digits aren't meaningful, unless you track floating point error.

If you want to show display answers with the same number of digits as the inputs, then this is actually a functional requirement.

**Comment by GenevaS** [comment]
Alright, I've added a new requirement for this issue. 

I have also added a couple new requirements related to issue #16. Could you please have a look at them and tell me if any are now redundant?

**Comment by smiths** [comment]
I'm sorry Geneva, but I really cannot review all of the changes in your document.  This just isn't fair to the other students.  If I review every change in your document, I should review every change in everyone's documents.

**Comment by GenevaS** [comment]
I did open this issue separately from the issues related to your comments/questions in the SRS. I believe that I have added an adequate fix for this one, so I will close the issue. Thank you for your patience :)
