### ISSUE TITLE
More Tests Needed About The Input Values

### ISSUE THREAD

**Issue by halonazhao** [GenevaS/CAS741#21]
Under Getting User Input Section, I think you already have enough tests for the F(v) term, but some situations may not be tested for x = [], y=[] terms.
1. The intervals of x, y may have some constraints with F(v). For example, when F(v) = x/y, the interval of y can not include 0 in it like [0, 1]. This case system may need an error message.
2. User may also did not enter right format of intervals, such as x = [2, -2]. If the program defaults the first value as the small one, this input may effect the correctness of the result.

**Comment by GenevaS** [comment]
Ok, I think I've covered everything. I added one test case for reordering domain boundaries and three cases for division by zero (min bound, max bound, and constant value).
