### ISSUE TITLE
Correctness of Operator Composition, Manually?

### ISSUE THREAD

**Issue by halonazhao** [GenevaS/CAS741#22]
https://github.com/GenevaS/CAS741/blob/ae076dab116cf5cd70d7cd7931d94f4573424834/Doc/TestPlan/TestPlan.tex#L861 In this test case, your test can automatically decompose the expression to the tree. But in https://github.com/GenevaS/CAS741/blob/ae076dab116cf5cd70d7cd7931d94f4573424834/Doc/TestPlan/TestPlan.tex#L1302, you said this test should be done manually. I think if in first case, you can test a multiple operator expression automatedly. Why do you have to test the second manually? If an expression can be decomposed successfully, it means that the expression exits. Did I understand right? I am not sure about this, but a bit confused.

**Comment by GenevaS** [comment]
In the concrete cases, I have a limited number of expressions that I use to test if a tree can be created from some given expression. The purpose of the manual induction tests is to prove that a function of *any* length can be decomposed by the program if some tree exists.

I was planning on using the concrete tests as base cases for this manual proof-by-induction test. Does that make sense?

**Comment by GenevaS** [comment]
A similar comment was left by @smiths that I think I have addressed, so I am closing this issue.
