### ISSUE TITLE
Correctness of Intervals as Base Numbers?

### ISSUE THREAD

**Issue by halonazhao** [GenevaS/CAS741#23]
https://github.com/GenevaS/CAS741/blob/ae076dab116cf5cd70d7cd7931d94f4573424834/Doc/TestPlan/TestPlan.tex#L718
In this section, you mentioned test-parse\_intervalWithInvalidExponent1, test-parse\_intervalWithInvalidExponent2, test-parse\_intervalWithInvalidExponent3, test-parse\_intervalWithInvalidExponent4, test-parse\_intervalWithInvalidExponent5. Do you mean to test x^1, x^2, x^3...? Because you only wrote one case x^2 but different intervals for x.

**Comment by GenevaS** [comment]
I only see two tests in the document, but there are five listed here. Where did you see the last three (test-parse_intervalWithInvalidExponent3, test-parse_intervalWithInvalidExponent4, test-parse_intervalWithInvalidExponent5)?
