### ISSUE TITLE
MG - Interval and Equation Data Structure Modules

### ISSUE THREAD

**Issue by aoananp** [GenevaS/CAS741#27]
https://github.com/GenevaS/CAS741/blob/13090fb94cf52c69ee3dc37d9d8509741cf0d4a6/Doc/Design/MG/MG.tex#L394

Will you be implementing these modules or using a built-in library?
If these aren't part of the SRS, it would be good to have a more detailed requirement/spec in the MIS. :)

**Comment by GenevaS** [comment]
I am planning on implementing these myself (mainly because I need the  practice). These modules actually do directly follow from data definition and instance models in the SRS, so hopefully that is sufficient for their descriptions :)
