### ISSUE TITLE
MIS: Equation Data Structure

### ISSUE THREAD

**Issue by icbicket** [GenevaS/CAS741#31]
I'm a bit confused by this module, it seems like it should be defining a data type 'equationStruct', but I don't see this definition anywhere inside. It's a little confusing that the input to the EquationStruct program includes an equationStruct (and so does the output). If you're defining the equationStruct datatype in this module, why does it need that data type as an input? It seems like you have a cyclic definition here. Otherwise, what is an equationStruct?

**Comment by GenevaS** [comment]
Ah, I think this comes down to an inadequate definition of how I create objects in the program. A related comment was left by @smiths .

What I am trying to convey is that the EquationStruct objects can be linked to form a binary tree. I will be revising my documentation to make their creation process clearer.
