### ISSUE TITLE
MIS Consolidate Assumptions & Access Programs

### ISSUE THREAD

**Issue by icbicket** [GenevaS/CAS741#33]
There are some assumptions you make (thinking specifically of 10.4.2, maybe there are others), where you assume that another access program in the same module has been run first before running the second. Maybe instead of adding this assumption, you can raise an Exception if the necessary order has not been followed. 

Or even, since in the Control Flow, you run all three of the Consolidate functions in sequence with each other, with no interruptions to run other modules, maybe you can combine all three into one access program that does all three tasks? And looking at it more closely, the second two access programs are Getters for the state variables created with the first, why not return these variables as output from ConvertAndCheckInputs instead? Maybe having the Getters as independent access programs is not so useful to the code.

**Comment by GenevaS** [comment]
I ended up not needing the Assumptions for Consolidate, so I removed them.

My ControlFlow module has changed considerably after implementation, so I don't know if the same issues apply. However, having independent getters was a design decision I made knowing that the implementation language (C#) cannot return multiple values of different types. Having the getter functions individually also lets me access the state variables at any time in the process, not just when they are calculated. This is an added bit of flexibility for not a lot of work, so I usually include them in my programs.
