### ISSUE TITLE
MIS: supportedOps

### ISSUE THREAD

**Issue by icbicket** [GenevaS/CAS741#35]
Is it useful to you to have a supportedOps abstract data type? It will make it clear in the MIS/MG which operators the user is allowed to have, and the program will have somewhere to keep its knowledge of which operators are acceptable. Maybe it will also make it easier to expand to new operators or change the allowed inputs later. Or maybe the supportedOps should be state variables held in a different module?

**Comment by GenevaS** [comment]
I agree and have already added it (Operator Data Structure). I might have committed it here while you were reading the document :)
