### ISSUE TITLE
Relationship between theoretical models, data definitions, and instance models

### ISSUE THREAD

**Issue by GenevaS** [GenevaS/CAS741#4]
Hi Professor.

I am still not sure that I understand the breakdown of my project into the different model sections. 

I have used the theoretical models section to write interval arithmetic in set representation (which can potentially be implemented different ways), the data definitions to outline the notation used in the instance models (as a way to make a concrete data definition that elements in the theoretical models), and the instance models to express a concrete method of calculating interval values. Is this the correct way to approach it?

The most recent version of the SRS is [here](https://github.com/GenevaS/CAS741/blob/master/Doc/SRS/SRS.pdf) with partially filled out model specifications. 

Thanks for looking at this!

**Comment by smiths** [comment]
Hello @GenevaS.  I took a quick look and I like what I see.  Your theory is general and then you introduce the two boundary point representation of an interval.  If you don't make it clear, you should point out that there are other representations for intervals, such as the midpoint radius representation.

DD2 and DD3 seem rather trivial. You could probably handle these through the table of symbols.

It looks like you don't have functions (like sine, cosine etc.).  If that is the case, you should make it clear that these are outside of your scope.

**Comment by GenevaS** [comment]
Alright, I will move DD2 and 3 to the table of symbols and use the data constraints to cover the specifics. I will also make it more specific in the assumptions that trigonometric functions aren't being covered in the initial version. Perhaps it should be a new assumption (rather than extending the accepted operators assumption [A3])?

**Comment by smiths** [comment]
Hi Geneva.  Yes, I like the idea of a new assumption.  Your initial version only has the basic arithmetic operations.  You can make that an assumption.  For future versions this assumption can be removed.

**Comment by GenevaS** [comment]
Alright, these items have been fixed in commits e27aa7355b120b349ebfc8b5d953293bd5bc7e87 and 4db345d9920869c0dd9462907b07d6a34216c03c. Thanks for your help!
