### ISSUE TITLE
Formatting the Data Constraints Section

### ISSUE THREAD

**Issue by GenevaS** [GenevaS/CAS741#5]
Hi Professor.

While I was filling in the data constraint tables from the project template, I found that many of the columns did not apply to my specification. Rather than having two mostly empty tables, I decided to format this section the same way as the medical imaging tool (3dfim+). This condensed my constraints into two lists (input and output). 

Is this approach acceptable for this project, or should I stick with the template tables? Thanks!

Here is a direct link to the SRS PDF: https://github.com/GenevaS/CAS741/blob/master/Doc/SRS/SRS.pdf

**Comment by smiths** [comment]
Sounds good @GenevaS.  I agree with your choice to use the same approach as the medical imaging example.
