### ISSUE TITLE
User responsibility

### ISSUE THREAD

**Issue by renjiezhang** [GenevaS/CAS741#7]
@GenevaS @smiths 
In user responsibilities section, one of responsibilities is to ensure the calculator outputs are semantically correct with respect to the target application. I don't quite understand why this is supposed to be one of user responsibilities. I think it is the software's responsibility because it is the program to output the result.

**Comment by GenevaS** [comment]
The C^3 tool does not know what you are testing the equation for, which also means it cannot know that the [-2,3] range it found for your equation is not the [-1,1] range that you are trying to achieve. It can only tell you what it is (if it exists), not if it is what you wanted.

Still, I think that this can be rewritten to be clearer and has been done so in f1fb265b61920373f8e6ffce2be9d5ecb65fb68a:

"Determine if the C^3 outputs are appropriate for the intended application and make adjustments to the program inputs as required"
